server:
    port: 8080

spring : 
    datasource:
        url: jdbc:mysql://localhost/trial
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate.ddlAuto: update
        generate-ddl: true
        show-sql: true

    mvc:
        view:
            prefix: /
            suffix: .html   
            
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
#            
#file:
#    upload-dir= ./uploads
#            
            
spring.jackson.default-property-inclusion: NON_NULL
spring.freemarker.suffix: .html
